// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Hotel_Reservation.Models;

public partial class Billing
{
    public int BillingId { get; set; }

    public int? BookingId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime PaymentDate { get; set; }

    [JsonIgnore]
    public virtual Booking Booking { get; set; }
}