// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Hotel_Reservation.Models;

public partial class BookingService
{
    public int BookingId { get; set; }

    public int ServiceId { get; set; }

    public int Quantity { get; set; }

    [JsonIgnore]
    public virtual Booking Booking { get; set; }
    [JsonIgnore]
    public virtual Service Service { get; set; }
}