// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Hotel_Reservation.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public string GuestId { get; set; }

    public int? RoomId { get; set; }

    public DateOnly? CheckIn { get; set; }

    public DateOnly? CheckOut { get; set; }

    public decimal TotalAmount { get; set; }

    public bool? Confirmation { get; set; }

    public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;

    [JsonIgnore]
    public virtual ICollection<Billing> Billings { get; set; } = new List<Billing>();
    [JsonIgnore]
    public virtual ICollection<BookingService> BookingServices { get; set; } = new List<BookingService>();
    [JsonIgnore]
    public virtual Guest Guest { get; set; }
    [JsonIgnore]
    public virtual Room Room { get; set; }
}