// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Hotel_Reservation.Models;

public partial class RoomAmenity
{
    public int RoomId { get; set; }

    public int AmenityId { get; set; }

    public int? Quantity { get; set; }

    [JsonIgnore]
    public virtual Amenity Amenity { get; set; }
    [JsonIgnore]
    public virtual Room Room { get; set; }
}