// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Hotel_Reservation.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public string RoomNumber { get; set; }

    public int? RoomTypeId { get; set; }

    public int Capacity { get; set; }

    public decimal PricePerNight { get; set; }

    public bool Availability { get; set; } = true;

    public string Location { get; set; }

    public string Description { get; set; }

    [JsonIgnore]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
    [JsonIgnore]
    public virtual ICollection<RoomAmenity> RoomAmenities { get; set; } = new List<RoomAmenity>();
    [JsonIgnore]
    public virtual RoomType RoomType { get; set; }
}