// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Hotel_Reservation.Models;

public partial class RoomType
{
    public int RoomTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    [JsonIgnore]
    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}